# Utilise une image officielle Python comme image de base
FROM python:3.11-slim

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie le fichier requirements (avec les dépendances Python) dans le conteneur
COPY requirements.txt .

# Installe les dépendances nécessaires
RUN pip install --no-cache-dir -r requirements.txt

# Copie tout le contenu de ton projet dans le conteneur
COPY . .

# Expose le port 5000 si tu as une interface web à lancer (sinon, modifie-le selon ton besoin)
EXPOSE 5000

# Commande pour lancer ton application, à ajuster selon ton besoin
CMD ["python", "main.py"]
