name: Run Docker Task

on:
  schedule:
    - cron: '59 19 * * *'  # Planifie à 10h05 UTC chaque jour

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null
          then
            echo "Docker is not installed. Installing Docker."
            sudo apt-get update
            sudo apt-get install -y docker.io
          else
            echo "Docker is already installed."
          fi
        
      - name: Check if Docker image exists locally
        run: |
          if ! docker image inspect sncf_analysis &> /dev/null; then
            echo "Docker image does not exist. Building the image."
            docker build -t sncf_analysis .
          else
            echo "Docker image exists. Skipping build."
          fi

      - name: Check if container is running
        run: |
          if [ "$(docker ps -q -f name=sncf_analysis_container)" ]; then
            echo "Container is already running."
          elif [ "$(docker ps -aq -f name=sncf_analysis_container)" ]; then
            echo "Container exists but is stopped. Restarting it."
            docker restart sncf_analysis_container
          else
            echo "Container does not exist. Creating and starting a new container."
            docker run -d --name sncf_analysis_container -v $(pwd)/output:/app/output rosinesoro/sncf_analysis:latest  # Utilise l'image Docker
          fi

         
    - name: Retrieve CSV files from container
      run: |
        if ls ./output/*.csv 1> /dev/null 2>&1; then
          echo "CSV files generated successfully."
        else
          echo "No CSV files generated."
        fi

    - name: Upload CSV files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sncf_results
        path: ./output/*.csv  # Upload all CSV files generated